# format = """
# [â–‘â–’â–“](#a3aed2)\
# [ îœ’ ](bg:#a3aed2 fg:#090c0c)\
# $localip\
# [î‚°](bg:#769ff0 fg:#a3aed2)\
# $directory\
# [î‚°](fg:#769ff0 bg:#394260)\
# $git_branch\
# $git_status\
# [î‚°](fg:#394260 bg:#212736)\
# $kubernetes\
# $rust\
# $python\
# $nodejs\
# $golang\
# $openstack\
# [î‚°](fg:#212736 bg:#1d2230)\
# $time\
# [î‚° ](fg:#1d2230)\
# \n$character"""

#[directory]
#style = "fg:#e3e5e5 bg:#769ff0"
#format = "[ $path ]($style)"
#truncation_length = 3
#truncation_symbol = "â€¦/"
#
#[username]
#show_always = true
#style_user = "bold 199"
#format = "[$user]($style) in "
#
#[directory.substitutions]
#"Documents" = "ó°ˆ™ "
#"Downloads" = "ï€™ "
#"Music" = "ï€ "
#"Pictures" = "ï€¾ "

#[git_branch]
#symbol = "ï˜"
#style = "bg:#394260"
#format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'
#
#[git_status]
#style = "bg:#394260"
#format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
#
#[nodejs]
#symbol = "îœ˜"
#style = "bg:#212736"
#format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
#
#[python]
#symbol = "îˆµ "
#style = "bg:#212736"
#format = '[[ $symbol ($pyenv_prefix)($version) (\($virtualenv\)) ](fg:#769ff0 bg:#212736)]($style)'
#
#[rust]
#symbol = "î¨"
#style = "bg:#212736"
#format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
#
#[golang]
#symbol = "î˜§"
#style = "bg:#212736"
#format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
#
#[php]
#symbol = "î˜ˆ"
#style = "bg:#212736"
#format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
#
[time]
disabled = false
#time_format = "%R" # Hour:Minute Format
#style = "bg:#1d2230"
format = '[[ ïº $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[kubernetes]
format = '[$symbol](bright-black) [$context( \($namespace\))]($style)'
disabled = false
symbol = "âˆ"
contexts = [
  { context_pattern = "ciab", style = "green" },
  { context_pattern = ".*kind.*", style = "green" },
  { context_pattern = ".*dev.*", style = "yellow" },
  { context_pattern = ".*prod.*", style = "red", symbol = "ğŸ”¥ " }
]

[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = false

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false
